# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_subcluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcluster',
            name='group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcluster',
            name='subcluster',
            field=models.IntegerField(),
        ),
    ]
