# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_auto_20170331_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcluster',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.Cluster'),
        ),
    ]
