# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_auto_20170331_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='num_of_clusters',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
