# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0008_auto_20170403_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
